query($search: String, $page: Int, $perPage: Int, $type: String) {
  Page(page: $page, perPage: $perPage) {
    media(search: $search) {
      id
      title {
        english
        romaji
        native
      }
      description(ashtml: true)
      format
      averageScore
      meanScore
      coverImage {
        medium
      }
    }
  }
}